stages:
  - build
  - tests
  - publish_images

variables:
  BUILDANGULAR_VERSION: '0.0.6'
  BASE_IMAGE_NAME: 'article714/build-angular'

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--network=internal_bridge --force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} -t ${BASE_IMAGE_NAME}:${BUILDANGULAR_VERSION} --build-arg BUILDANGULAR_VERSION=${BUILDANGULAR_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: ${BASE_IMAGE_NAME}:${BUILDANGULAR_VERSION}
  services:
    - name: ${BASE_IMAGE_NAME}:${BUILDANGULAR_VERSION}
      alias: odoo-srv
  tags:
    - docker
  script:
    # wait for bindns to be fully fit
    - echo "TODO"
    - git --version
